Updated gradle version and subsequent file fixes for Ghidra 11.2
DSecurity/efiSeek pull request #16
Opened 2024-10-29 18:51 UTC by DisplayGFX

This should work for Ghidra versions 11.2 and after.

I updated gradle and its wrapper to 8.10, so the build file needed to be altered due to version changes, but unclear if what I did was the intended way of fixing it.

Resolves #15

2024-12-16 23:15 UTC, jwise commented
Works for me.  Thanks!

2025-01-17 00:24 UTC, jaredmauch requested changes
Suggest updating to gradle-8.12-bin.zip  I was just going to send a PR for that, hopefully someone can merge :-)

2025-05-26 03:25 UTC, gfanini commented
possibly could build.gradle be 

configurations {
    toCopy
	 implementation {
        extendsFrom toCopy
    }
}

dependencies {
    toCopy 'org.json:json:20200518'      
    //implementation configurations.toCopy    
}
to match ghidra 11
distributionUrl=https\://services.gradle.org/distributions/gradle-8.12.1-bin.zip

but then I get 
Execution failed for task ':compileJava'.
> error: invalid source release: 21
what should be changed, I am using java open jkd 11

2026-06-27 19:07 UTC, closed without merging

2026-06-27 19:07 UTC, DisplayGFX commented
closing, #19 superseeds this pull